$schema: "http://json-schema.org/draft-07/schema#"
description: Schema for config.yaml for bacterial_strains_from_metagenomes pipeline
type: object
properties:
  genome_database_dir:
    type: string
    description: Path to the directory containing genome database files
  samples_csv:
    type: string
    description: Path to the CSV file containing sample information
    pattern: ".*\\.csv$"
  results_dir:
    type: string
    description: Path to the output results directory
  resources_dir:
    type: string
    description: Path to the resources directory for persistent files
  params:
    type: object
    description: Parameters for tools used in the pipeline
    properties:
      prodigal:
        type: object
        properties:
          mode:
            type: string
            enum: ["single", "meta"]
      bowtie2_build:
        type: object
        properties:
          threads:
            type: integer
            minimum: 1
      bowtie2_map:
        type: object
        properties:
          threads:
            type: integer
            minimum: 1
          extra:
            type: string
  instrain:
    type: object
    description: Parameters for inStrain analysis
    properties:
      threads:
        type: integer
        minimum: 1
      memory_mb:
        type: integer
        minimum: 1000
      time_min:
        type: integer
        minimum: 1
      min_read_ani:
        type: number
        minimum: 0
        maximum: 1
      min_mapq:
        type: integer
        minimum: 0
      min_coverage:
        type: integer
        minimum: 1
      profile_extra:
        type: string
      compare_extra:
        type: string
required:
  - genome_database_dir
  - samples_csv
  - results_dir
  - resources_dir
additionalProperties: true 